"""Initial migration

Revision ID: 35b22e9df5a1
Revises: 
Create Date: 2025-01-19 22:49:02.080003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35b22e9df5a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countries')
    op.create_unique_constraint(None, 'company', ['company_id'])
    op.alter_column('promo_code', 'mode',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('COMMON', 'UNIQUE', name='promomode'),
               existing_nullable=False)
    op.alter_column('promo_code', 'active_from',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('promo_code', 'active_until',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('promo_code', 'created',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'promo_code', ['promo_id'])
    op.alter_column('promo_code_statistics', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('promo_code_statistics', 'activations_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('promo_code_statistics_unique', 'promo_code_statistics', type_='unique')
    op.create_index(op.f('ix_promo_code_statistics_id'), 'promo_code_statistics', ['id'], unique=False)
    op.alter_column('user', 'avatar_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'avatar_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_promo_code_statistics_id'), table_name='promo_code_statistics')
    op.create_unique_constraint('promo_code_statistics_unique', 'promo_code_statistics', ['id'])
    op.alter_column('promo_code_statistics', 'activations_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('promo_code_statistics', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'promo_code', type_='unique')
    op.alter_column('promo_code', 'created',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('promo_code', 'active_until',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('promo_code', 'active_from',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('promo_code', 'mode',
               existing_type=sa.Enum('COMMON', 'UNIQUE', name='promomode'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'company', type_='unique')
    op.create_table('countries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('alpha2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('alpha3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('region', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='countries_pkey')
    )
    # ### end Alembic commands ###
